version: '3'

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

  web:
    env_file: .env
    build: .
    command: /src/entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redisdata:
